### ISSUE TITLE
Error loading pre-trained Dit model: Size mismatches in pos_embed, x_embedder, and final_layer parameters

### ISSUE THREAD

**Issue by dkx2077** [jinyeying/RaindropClarity#9]
**Description**

I encountered errors while running the official evaluation code with the provided pre-trained Dit model. The model fails to load due to size mismatches in several parameters. Specifically, the error mentions mismatches in:

- `module.pos_embed`: checkpoint shape is `[1, 1024, 768]` vs. model expecting `[1, 256, 768]`
- `module.x_embedder.proj.weight`: checkpoint shape is `[768, 6, 2, 2]` vs. model expecting `[768, 6, 4, 4]`
- `module.final_layer.linear.weight`: checkpoint shape is `[12, 768]` vs. model expecting `[48, 768]`
- `module.final_layer.linear.bias`: checkpoint shape is `[12]` vs. model expecting `[48]`

It appears that the model architecture defined in the configuration does not match the pre-trained checkpoint.

---

**Steps to Reproduce**

1. **Clone the repository** and set up the environment.
2. **Download** the provided pre-trained Dit model checkpoint located at:
   ```
   /xxxxxxx/Raindrop_DiT/NightRaindrop_DiT_ddpm.pth.tar
   ```
3. **Run the evaluation script** using:
   ```bash
   bash run_eval_diffusion_night.sh
   ```
4. The error occurs during the checkpoint loading phase in the `DiffusiveRestoration` initialization.

---

**Configuration File**

Below is the content of the configuration file (`nighttime_64.yml`) used in the experiment:

```yaml
data: 
    dataset: "NightRaindrop"
    image_size: 64  # Raindrop_DiT, RDiffusion, onego
    channels: 3
    num_workers: 8
    data_dir: "/root/autodl-tmp/NightRainDrop/"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 4
    batch_size: 16
    n_epochs: 37042
    n_iters: 20000000
    snapshot_freq: 10000
    validation_freq: 10000

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
```

---

**Error Log Excerpt**

```
RuntimeError: Error(s) in loading state_dict for DataParallel:
        size mismatch for module.pos_embed: copying a param with shape torch.Size([1, 1024, 768]) from checkpoint, the shape in current model is torch.Size([1, 256, 768]).
        size mismatch for module.x_embedder.proj.weight: copying a param with shape torch.Size([768, 6, 2, 2]) from checkpoint, the shape in current model is torch.Size([768, 6, 4, 4]).
        size mismatch for module.final_layer.linear.weight: copying a param with shape torch.Size([12, 768]) from checkpoint, the shape in current model is torch.Size([48, 768]).
        size mismatch for module.final_layer.linear.bias: copying a param with shape torch.Size([12]) from checkpoint, the shape in current model is torch.Size([48]).
```

---
